window.MOWA_QUESTIONNAIRE = {
  scaleLabels: {
    importance: ["Not important", "Slightly", "Moderately", "Very", "Essential"],
    performance: ["Poorly", "Below average", "Adequately", "Well", "Very well"],
    value: ["Not valuable", "Slightly", "Moderately", "Very", "Essential"],
    alignment: ["Not aligned", "Weak", "Somewhat", "Well", "Strong"],
    urgency: ["Not urgent", "Slight", "Moderate", "Very", "Critical"],
    concern: ["Not concerned", "Slight", "Moderate", "Very", "Extreme"]
  },
  sections: [
    {
      id: "profile",
      eyebrow: "Section 1",
      title: "About you",
      intro: "These questions help separate board, longtime member, newer member, student, and prospective-member perspectives.",
      questions: [
        { id: "role", type: "radio", required: true, label: "What is your current relationship to MOWA?", options: ["Current Board member", "Current active member", "Apprentice member", "Supporting member", "Past member", "Prospective member", "Other"] },
        { id: "mowa_years", type: "radio", label: "How long have you been involved with MOWA?", options: ["Less than 1 year", "1–3 years", "4–10 years", "11–20 years", "More than 20 years", "Not currently involved"] },
        { id: "creator_types", type: "checkbox", label: "What type of outdoor communication do you currently do? Select all that apply.", options: ["Writing / journalism", "Photography", "Video / filmmaking", "Podcasting / audio", "Radio / television", "Blogging / websites", "Social media / digital content", "Books", "Public relations / communications", "Conservation / nonprofit communication", "Tourism / destination communication", "Outdoor education", "I do not currently produce outdoor communication", "Other"] },
        { id: "work_status", type: "radio", label: "Which best describes your current outdoor communication work?", options: ["Full-time paid work", "Part-time paid work", "Occasional paid work", "Volunteer / unpaid but serious work", "Student / emerging communicator", "Retired from active outdoor communication", "Supporter, but not a creator"] },
        { id: "age_range", type: "radio", label: "Optional: What age range are you in?", options: ["Under 25", "25–34", "35–44", "45–54", "55–64", "65–74", "75+", "Prefer not to answer"] },
        { id: "gender", type: "radio", label: "Optional: How do you describe your gender?", options: ["Woman", "Man", "Nonbinary", "Prefer to self-describe", "Prefer not to answer"] }
      ]
    },
    {
      id: "expectations",
      eyebrow: "Section 2",
      title: "What should MOWA be?",
      intro: "Rate how important each area should be to MOWA’s future. This establishes member expectations before judging current performance.",
      questions: [
        { id: "imp_writers", type: "scale", scale: "importance", label: "Supporting professional outdoor writers." },
        { id: "imp_multimedia", type: "scale", scale: "importance", label: "Supporting photographers, videographers, podcasters, website creators, social media creators, and other outdoor media professionals." },
        { id: "imp_craft", type: "scale", scale: "importance", label: "Helping members improve their craft." },
        { id: "imp_opportunities", type: "scale", scale: "importance", label: "Helping members find professional opportunities, contacts, assignments, or collaborations." },
        { id: "imp_networking", type: "scale", scale: "importance", label: "Providing networking between members, editors, agencies, outdoor organizations, brands, and conservation groups." },
        { id: "imp_mentoring", type: "scale", scale: "importance", label: "Mentoring younger or newer outdoor communicators." },
        { id: "imp_students", type: "scale", scale: "importance", label: "Recruiting students and early-career creators." },
        { id: "imp_women_broader", type: "scale", scale: "importance", label: "Recruiting more women and a broader range of outdoor voices." },
        { id: "imp_conservation", type: "scale", scale: "importance", label: "Promoting conservation, natural resources, clean water, and responsible outdoor recreation." },
        { id: "imp_heritage", type: "scale", scale: "importance", label: "Preserving MOWA history, traditions, memorials, awards, and legacy." },
        { id: "imp_public_voice", type: "scale", scale: "importance", label: "Serving as a public-facing voice for outdoor communication in Michigan." },
        { id: "imp_media_change", type: "scale", scale: "importance", label: "Helping members adapt to changes in media, publishing, technology, and audience behavior." },
        { id: "imp_visibility", type: "scale", scale: "importance", label: "Making MOWA more visible to the public and prospective members." },
        { id: "imp_current_members", type: "scale", scale: "importance", label: "Making MOWA more useful to current members." },
        { id: "purpose_today", type: "textarea", label: "In one sentence, what do you believe MOWA’s main purpose should be today?" },
        { id: "must_not_lose", type: "textarea", label: "In one sentence, what do you believe MOWA must not lose as it changes?" }
      ]
    },
    {
      id: "performance",
      eyebrow: "Section 3",
      title: "How well is MOWA doing now?",
      intro: "Rate current performance honestly. The biggest insight comes from comparing these scores against the importance scores above.",
      questions: [
        { id: "perf_writers", type: "scale", scale: "performance", na: true, label: "Supporting outdoor writers." },
        { id: "perf_multimedia", type: "scale", scale: "performance", na: true, label: "Supporting photographers, videographers, podcasters, websites, digital creators, and other nontraditional outdoor communicators." },
        { id: "perf_craft", type: "scale", scale: "performance", na: true, label: "Helping members improve their craft." },
        { id: "perf_opportunities", type: "scale", scale: "performance", na: true, label: "Helping members find opportunities, contacts, assignments, or collaborations." },
        { id: "perf_networking", type: "scale", scale: "performance", na: true, label: "Providing valuable networking." },
        { id: "perf_mentoring", type: "scale", scale: "performance", na: true, label: "Mentoring younger or newer communicators." },
        { id: "perf_students", type: "scale", scale: "performance", na: true, label: "Recruiting students and early-career creators." },
        { id: "perf_women_broader", type: "scale", scale: "performance", na: true, label: "Recruiting women and a broader range of outdoor voices." },
        { id: "perf_conservation", type: "scale", scale: "performance", na: true, label: "Promoting conservation, natural resources, clean water, and responsible outdoor recreation." },
        { id: "perf_heritage", type: "scale", scale: "performance", na: true, label: "Preserving MOWA history and legacy." },
        { id: "perf_member_comm", type: "scale", scale: "performance", na: true, label: "Communicating clearly with current members." },
        { id: "perf_public_comm", type: "scale", scale: "performance", na: true, label: "Communicating clearly with prospective members." },
        { id: "perf_website", type: "scale", scale: "performance", na: true, label: "Keeping the website current, useful, and welcoming." },
        { id: "perf_social", type: "scale", scale: "performance", na: true, label: "Keeping social media or public communications active and appealing." },
        { id: "perf_membership_process", type: "scale", scale: "performance", na: true, label: "Making the membership process easy to understand." },
        { id: "perf_welcome_outsiders", type: "scale", scale: "performance", na: true, label: "Making new people feel welcome if they do not already know current members." },
        { id: "perf_adapt_media", type: "scale", scale: "performance", na: true, label: "Helping MOWA adapt to current outdoor media trends." },
        { id: "perf_current_members", type: "scale", scale: "performance", na: true, label: "Overall, how well is MOWA serving its current members?" },
        { id: "perf_new_members", type: "scale", scale: "performance", na: true, label: "Overall, how well is MOWA positioned to attract new members over the next 5 years?" },
        { id: "does_well", type: "textarea", label: "What is MOWA currently doing well?" },
        { id: "not_well", type: "textarea", label: "What is MOWA currently not doing well?" },
        { id: "do_not_drop", type: "textarea", label: "What is one thing MOWA does that you value and would not want to see disappear?" },
        { id: "less_useful", type: "textarea", label: "What is one thing MOWA does that may no longer be as useful as it once was?" }
      ]
    },
    {
      id: "activities",
      eyebrow: "Section 4",
      title: "Existing activities and structures",
      intro: "This section looks at the things MOWA already does and asks whether they actually serve the purposes members care about.",
      questions: [
        { id: "conference_importance", type: "scale", scale: "importance", label: "Importance of the annual conference." },
        { id: "conference_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of the annual conference." },
        { id: "conference_improve", type: "textarea", label: "What would make the annual conference more valuable or attractive?" },
        { id: "awards_importance", type: "scale", scale: "importance", label: "Importance of craft or excellence awards." },
        { id: "awards_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of current award categories." },
        { id: "awards_reflect_today", type: "radio", label: "Do the current award categories reflect the kinds of outdoor media being created today?", options: ["Yes", "Mostly", "Somewhat", "No", "Not sure"] },
        { id: "awards_changes", type: "textarea", label: "What award categories, if any, should be added or changed?" },
        { id: "emerging_importance", type: "scale", scale: "importance", label: "Importance of apprentice or emerging-member pathways." },
        { id: "emerging_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of current apprentice or emerging-member pathways." },
        { id: "emerging_support", type: "textarea", label: "How could MOWA better support students, younger members, or early-career creators?" },
        { id: "standards_importance", type: "scale", scale: "importance", label: "Importance of maintaining professional standards for membership." },
        { id: "standards_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of current membership requirements in protecting professional standards." },
        { id: "recruitment_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of current membership requirements in attracting new members." },
        { id: "membership_welcoming", type: "radio", label: "Does the current membership process feel welcoming to people who do not already know a MOWA member?", options: ["Yes", "Mostly", "Somewhat", "No", "Not sure"] },
        { id: "serious_unpaid_path", type: "radio", label: "Should MOWA offer a clearer path for serious outdoor creators who are not yet regularly paid?", options: ["Yes", "Maybe", "No", "Not sure"] },
        { id: "digital_creator_path", type: "radio", label: "Should MOWA offer a clearer path for digital creators, podcasters, videographers, photographers, website publishers, and social media creators?", options: ["Yes", "Maybe", "No", "Not sure"] },
        { id: "membership_barrier", type: "textarea", label: "What membership requirement or process, if any, may discourage qualified or promising people from joining?" },
        { id: "website_importance", type: "scale", scale: "importance", label: "Importance of the website for recruiting new members." },
        { id: "website_recruiting", type: "scale", scale: "performance", na: true, label: "Effectiveness of the current website for recruiting new members." },
        { id: "website_current_members", type: "scale", scale: "performance", na: true, label: "Effectiveness of the current website for serving current members." },
        { id: "website_explains_belonging", type: "radio", label: "Does the website clearly explain who belongs in MOWA today?", options: ["Yes", "Mostly", "Somewhat", "No", "Not sure"] },
        { id: "website_feels_current", type: "radio", label: "Does the website make MOWA look active, current, and welcoming?", options: ["Yes", "Mostly", "Somewhat", "No", "Not sure"] },
        { id: "website_better", type: "textarea", label: "What should the website do better?" },
        { id: "public_comms_importance", type: "scale", scale: "importance", label: "Importance of active public communication outside the website." },
        { id: "public_comms_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of MOWA’s current public communication outside the website." },
        { id: "audiences_reach", type: "textarea", label: "What audiences should MOWA try harder to reach?" },
        { id: "water_conservation_importance", type: "scale", scale: "importance", label: "Importance of conservation, natural resources, clean water, and outdoor ethics to MOWA’s identity." },
        { id: "water_conservation_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of MOWA’s current conservation-related activities or recognition programs." },
        { id: "more_conservation", type: "radio", label: "Should MOWA do more to connect outdoor communication with conservation and responsible recreation?", options: ["Yes", "Maybe", "No", "Not sure"] },
        { id: "conservation_role", type: "textarea", label: "What conservation-related role should MOWA play?" },
        { id: "heritage_importance", type: "scale", scale: "importance", label: "Importance of preserving MOWA history, memorials, and legacy programs." },
        { id: "heritage_effectiveness", type: "scale", scale: "performance", na: true, label: "Effectiveness of current heritage, memorial, or history-related efforts." },
        { id: "honor_history", type: "textarea", label: "How can MOWA honor its history while still becoming more attractive to new members?" }
      ]
    },
    {
      id: "future",
      eyebrow: "Section 5",
      title: "Potential future activities",
      intro: "Rate how valuable each possible activity would be. These are not decisions; they are a way to see where members see opportunity.",
      questions: [
        { id: "future_redesign", type: "scale", scale: "value", label: "A redesigned website focused on recruitment, member benefits, and current outdoor media." },
        { id: "future_who_can_join", type: "scale", scale: "value", label: "A clearer “Who Can Join?” page that includes writers, photographers, filmmakers, podcasters, digital creators, conservation communicators, and others." },
        { id: "future_no_sponsor", type: "scale", scale: "value", label: "A “No Sponsor? We’ll Connect You” pathway for qualified prospective members who do not know a current member." },
        { id: "future_student", type: "scale", scale: "value", label: "A student or emerging-creator membership category with lower cost and mentoring." },
        { id: "future_mentorship", type: "scale", scale: "value", label: "A formal mentorship program pairing experienced members with newer creators." },
        { id: "future_webinars", type: "scale", scale: "value", label: "Online workshops or webinars on writing, photography, video, podcasting, freelancing, ethics, conservation reporting, and digital publishing." },
        { id: "future_directory", type: "scale", scale: "value", label: "A member directory that helps members find collaborators, editors, photographers, speakers, podcast guests, and subject experts." },
        { id: "future_opportunity_board", type: "scale", scale: "value", label: "A job, assignment, pitch, or opportunity board." },
        { id: "future_partnerships", type: "scale", scale: "value", label: "More partnerships with universities, colleges, journalism programs, conservation organizations, tourism groups, agencies, and outdoor brands." },
        { id: "future_modern_awards", type: "scale", scale: "value", label: "Award categories for podcasting, video, websites, social media storytelling, newsletters, photo essays, conservation explainers, and digital projects." },
        { id: "future_member_spotlight", type: "scale", scale: "value", label: "A “member spotlight” series featuring current members’ work." },
        { id: "future_new_voices", type: "scale", scale: "value", label: "A “new voices in outdoor media” effort aimed at younger members, women, and people entering outdoor communication through newer platforms." },
        { id: "future_regional_meetups", type: "scale", scale: "value", label: "Regional meetups or informal outdoor/content gatherings between annual conferences." },
        { id: "future_social", type: "scale", scale: "value", label: "A stronger social media presence showing member work, conference activity, awards, conservation stories, and ways to join." },
        { id: "future_public_newsletter", type: "scale", scale: "value", label: "A public-facing email newsletter." },
        { id: "future_member_newsletter", type: "scale", scale: "value", label: "A private member newsletter with opportunities, deadlines, member news, and calls for collaboration." },
        { id: "future_portfolio_review", type: "scale", scale: "value", label: "A portfolio review or critique session for members and apprentice members." },
        { id: "future_growth_committee", type: "scale", scale: "value", label: "A Board-level membership growth committee." },
        { id: "future_comms_committee", type: "scale", scale: "value", label: "A Board-level website / communications / outreach committee." },
        { id: "future_mission_review", type: "scale", scale: "value", label: "A regular review of whether MOWA activities align with its mission, bylaws, and membership goals." },
        { id: "priority_one", type: "text", label: "Which potential activity should MOWA prioritize first?" },
        { id: "priority_two", type: "text", label: "Second priority?" },
        { id: "priority_three", type: "text", label: "Third priority?" },
        { id: "future_other", type: "textarea", label: "Are there any potential activities not listed above that MOWA should consider?" }
      ]
    },
    {
      id: "change",
      eyebrow: "Section 6",
      title: "Tradeoffs and readiness for change",
      intro: "This section gives change skeptics a fair place to speak and helps identify what must be preserved.",
      questions: [
        { id: "change_view", type: "radio", label: "Which statement best describes your view?", options: ["MOWA should mostly preserve its current structure and activities.", "MOWA should make small improvements but avoid major changes.", "MOWA should modernize some parts while preserving its core traditions.", "MOWA needs a significant overhaul to remain relevant.", "Not sure."] },
        { id: "urgency_new_members", type: "scale", scale: "urgency", label: "How urgent is the need to attract new members?" },
        { id: "concern_relevance", type: "scale", scale: "concern", label: "How concerned are you about MOWA’s ability to remain active and relevant over the next 5–10 years without meaningful changes?" },
        { id: "comfort_supporting_change", type: "textarea", label: "What would make you more comfortable supporting changes to MOWA?" },
        { id: "change_too_far", type: "textarea", label: "What kinds of changes would concern you or go too far?" },
        { id: "preserve_when_modernizing", type: "textarea", label: "If MOWA modernizes its website, membership messaging, award categories, and outreach, what should it be careful to preserve?" },
        { id: "no_change_future", type: "textarea", label: "If MOWA does not make meaningful changes, what do you think is likely to happen over the next 5–10 years?" },
        { id: "argument_keep", type: "textarea", label: "What is the strongest argument for keeping MOWA mostly as it is?" },
        { id: "argument_change", type: "textarea", label: "What is the strongest argument for changing MOWA?" }
      ]
    },
    {
      id: "alignment",
      eyebrow: "Section 7",
      title: "Mission, bylaws, and activity alignment",
      intro: "These questions make it possible to compare the survey results with MOWA’s stated mission and bylaws later.",
      questions: [
        { id: "align_professional", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities support professional outdoor communicators." },
        { id: "align_all_forms", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities support all major forms of outdoor communication, including writing, photography, video, audio, web, and digital media." },
        { id: "align_skills", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities help members improve their communication skills." },
        { id: "align_careers", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities help further members’ careers." },
        { id: "align_networking", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities provide meaningful networking opportunities." },
        { id: "align_next_gen", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities inspire and mentor the next generation of outdoor media professionals." },
        { id: "align_conservation", type: "scale", scale: "alignment", na: true, label: "MOWA’s current activities support conservation, natural resources, and responsible outdoor recreation." },
        { id: "align_membership", type: "scale", scale: "alignment", na: true, label: "MOWA’s current membership requirements support the organization’s stated purpose." },
        { id: "align_public_comms", type: "scale", scale: "alignment", na: true, label: "MOWA’s current public-facing communications support the organization’s stated purpose." },
        { id: "align_awards", type: "scale", scale: "alignment", na: true, label: "MOWA’s current awards and recognition programs support the organization’s stated purpose." },
        { id: "align_board", type: "scale", scale: "alignment", na: true, label: "MOWA’s current Board structure and committees support the organization’s stated purpose." },
        { id: "biggest_mismatch", type: "textarea", label: "Where do you see the biggest mismatch between MOWA’s stated purpose and what MOWA actually does?" },
        { id: "bylaw_barriers", type: "textarea", label: "Are there any bylaws, policies, traditions, or procedures that may prevent MOWA from fulfilling its current mission?" },
        { id: "bylaw_protect", type: "textarea", label: "Are there any bylaws, policies, traditions, or procedures that should be protected because they are essential to MOWA’s identity?" }
      ]
    },
    {
      id: "final",
      eyebrow: "Section 8",
      title: "Final questions",
      intro: "These open answers often produce the best language for board discussion and a future strategic plan.",
      questions: [
        { id: "most_important_new_members", type: "textarea", label: "What is the single most important thing MOWA should do to attract new members?" },
        { id: "most_important_existing", type: "textarea", label: "What is the single most important thing MOWA should do to better serve existing members?" },
        { id: "support_young", type: "textarea", label: "What is the single most important thing MOWA should do to support younger or emerging outdoor communicators?" },
        { id: "welcome_women", type: "textarea", label: "What is the single most important thing MOWA should do to welcome more women and a broader range of outdoor voices?" },
        { id: "stay_relevant", type: "textarea", label: "What is the single most important thing MOWA should do to stay relevant as outdoor media changes?" },
        { id: "five_years", type: "textarea", label: "What should MOWA look like five years from now?" },
        { id: "additional_comments", type: "textarea", label: "Any additional comments?" }
      ]
    }
  ],
  gapPairs: [
    { label: "Support outdoor writers", importance: "imp_writers", performance: "perf_writers" },
    { label: "Support multimedia/digital creators", importance: "imp_multimedia", performance: "perf_multimedia" },
    { label: "Craft improvement", importance: "imp_craft", performance: "perf_craft" },
    { label: "Opportunities / assignments / collaborations", importance: "imp_opportunities", performance: "perf_opportunities" },
    { label: "Networking", importance: "imp_networking", performance: "perf_networking" },
    { label: "Mentoring newer communicators", importance: "imp_mentoring", performance: "perf_mentoring" },
    { label: "Students and early-career creators", importance: "imp_students", performance: "perf_students" },
    { label: "Women and broader outdoor voices", importance: "imp_women_broader", performance: "perf_women_broader" },
    { label: "Conservation / natural resources / responsible recreation", importance: "imp_conservation", performance: "perf_conservation" },
    { label: "Heritage and legacy", importance: "imp_heritage", performance: "perf_heritage" },
    { label: "Adapting to media change", importance: "imp_media_change", performance: "perf_adapt_media" },
    { label: "Serving current members", importance: "imp_current_members", performance: "perf_current_members" },
    { label: "Annual conference", importance: "conference_importance", performance: "conference_effectiveness" },
    { label: "Awards / recognition", importance: "awards_importance", performance: "awards_effectiveness" },
    { label: "Emerging-member pathways", importance: "emerging_importance", performance: "emerging_effectiveness" },
    { label: "Membership standards vs recruitment", importance: "standards_importance", performance: "recruitment_effectiveness" },
    { label: "Website as recruitment tool", importance: "website_importance", performance: "website_recruiting" },
    { label: "Public communication beyond the website", importance: "public_comms_importance", performance: "public_comms_effectiveness" },
    { label: "Conservation programs", importance: "water_conservation_importance", performance: "water_conservation_effectiveness" },
    { label: "Heritage / memorial efforts", importance: "heritage_importance", performance: "heritage_effectiveness" }
  ]
};
